name: Get Version

on:
  push:
    branches:
      - "master"

jobs: 
  findVersion:
    runs-on: ubuntu-latest

    #Checking out branch
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: master

      #Reading version
      - name: Reading version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'package-lock.json'
          prop-path: 'version'
          run: echo ${{steps.version.outputs.prop}}




